language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - PLUGIN_NAME=Redsys
    - REQUIRE=""

  matrix:
    - CAKE_REF=2.x

matrix:
  include:
    - php: 5.6
      env:
        - PHPCS=1
    - php: 5.6
      env:
        - CODECOVERAGE=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
