language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - PLUGIN_NAME=Redsys
    - DEFAULT=1
    - CAKE_REF=2.10.13

matrix:
  include:
    - php: 5.6
      env:
        - DEFAULT=0 PHPCS=1
    - php: 5.6
      env:
        - DEFAULT=0 CODECOVERAGE=1

install:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_REF
  - cp -R ../cakephp-redsys plugins/$PLUGIN_NAME
  - chmod -R 777 ../cakephp/app/tmp
  - composer require "phpunit/phpunit=3.*||4.*||5.*"
  - echo "require_once dirname(APP) . DS . 'vendors' . DS . 'autoload.php';" >> app/Config/bootstrap.php

script:
  - if [[ "$DEFAULT" == "1" ]]; then ./lib/Cake/Console/cake test $PLUGIN_NAME All${PLUGIN_NAME} --stderr; fi
  - if [[ "$CODE_COVERAGE" == "1" ]]; then phpdbg -qrr vendors/bin/phpunit --coverage-clover=clover.xml; fi
  - if [[ "$PHPCS" == "1" ]]; then vendors/bin/phpcs --config-set installed_paths vendors/cakephp/cakephp-codesniffer; fi
  - if [[ "$PHPCS" == "1" ]]; then vendors/bin/phpcs -p --extensions=php --standard=CakePHP --ignore=vendor/ plugins/$PLUGIN_NAME; fi


after_success:
  - if [[ "$CODE_COVERAGE" == "1" ]]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false
