language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer update --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: false
