language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6

env:
  global:
    - PLUGIN_NAME=Sermepa
    - REQUIRE=""

  matrix:
    - CAKE_VERSION=2.6
    - CAKE_VERSION=2.7
    - CAKE_VERSION=2.8

matrix:
  include:
    - php: 5.4
      env:
        - CAKE_VERSION=2.6
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - git clone -b master https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
